name: All recent posts
on:
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch:

jobs:
  readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: sarisia/actions-readme-feed@v1
        id: feed
        with:
          file: 'profile/README.md'
          format: '- ${monthlong} ${day} — [${title}](${url})'
          timezone: 'Europe/Amsterdam'
          url: |
            https://gethyas.com/index.xml
            https://getdoks.org/index.xml
      - if: ${{ steps.feed.outputs.changed == true }}
        uses: sarisia/actions-commit@master
